<!DOCTYPE html>
<html>
<head>
	<title>Promise</title>
	<script type="text/javascript">
		/*
			异步

			在JavaScript的世界中，所有代码都是单线程执行的。

			浏览器把一些耗时的事情通过新开线程的方式来实现

			把这些任务称为异步任务
			
			js中以异步实现的有：
			-setTimeout
			-setInterval
			-ajax
			
			异步是通过新开线程来实现一种非阻塞的方式执行代码
			同步是以当前线程实现一种阻塞的方式执行代码。

			异步有它的优点，也有它的缺点，

			优点：即使前面的代码没有执行完，也不影响后面代码的执行。

			缺点：
			1、对编程人员不友好，给阅读代码带来一些困扰。（因为异步的缘故，代码的执行顺序并会有一些错乱）
			function callback() {
			    console.log('Done');
			}
			console.log('before setTimeout()');
			setTimeout(callback, 1000); // 1秒钟后调用callback函数
			console.log('after setTimeout()');

			观察上述代码执行，在控制台输出可以看到：
			before setTimeout()
			after setTimeout()
			(等待1秒后)
			Done


			2、异步是以一种回调的方式告诉主线程代码执行的结果，有时的需求是需要知道结果之后才能继续后面的代码，比如需要知道ajax请求的结果才能继续请求另一个ajax，造成一种回调地狱

			回调地狱：
			比如获取当前用户信息，需要知道用户的身份是管理员还是其他，从而分配不同的权限，请求不一样的数据，然后再根据不一样的数据请求不一样的数据。这就造成ajax里嵌套ajax。我们称之为回调地狱。
			
			还有一种可能，需要请求两个ajax，然后根据这两个ajax返回的结果进行合并才能请求第三个ajax，那么这第三个ajax要放在前面哪个请求的结果里呢？

			
			ES6新增的promise对象就是用来解决这些问题。
			

			promise，构造函数，通过promise来构建一个异步任务处理对象。（把一个异步任务放到promise里面）
			

			Promise内会返回一个状态，分别有:
			pending:初始状态，既不是成功，也不是失败。
			resolved：操作成功
			rejected：操作失败

			这些状态由编程人员来设置。
			然后根据返回的状态成功与否来决定是执行then还是catch

		*/

		new Promise((resolve,reject) => { //参数名可自定义
				//resolve:函数，可传参到then方法，当我们调用该函数时，可以把当前Promise对象的任务状态改成resolved（成功）
				//reject:函数，可传参到then方法，当我们调用该函数时，可以把当前Promise对象的任务状态改成rejected（失败）

				//要执行的异步任务
				setTimeout(() =>{
					var a = 10;
					//resolve(a);//调用此方法后，then方法马上被执行
					reject('失败了');
				},1000);
			}).then( a =>{//then方法就是Promise处理完成后执行的方法
			//第一个方法在resolved（成功）状态时执行
				console.log(a)
			},err =>{//第二个方法在rejected（失败）状态时执行
				console.log(err)
			})




			//任务链
			new Promise((resolve,reject) => {
				resolve()
			}).then( //第一个then处理上一个Promise返回的状态
				()=>{ //处理成功时的方法
					console.log(1)
				},
				()=>{ //处理失败时的方法
					console.log(2)
				}
			).then( // 第二个then是处理上一个then返回的状态
				()=>{ //处理成功时的方法
					console.log(3)
				},
				()=>{ //处理成功时的方法
					console.log(4)
				}
			)

			//then函数执行后会返回一个新的Promise对象
				//如果ther没有传入处理函数，那么会返回一个继承了上一个处理状态的Promise对象
				new Promise((resolve,reject) => {
					resolve()
				}).then().then(//第二个then会继承上一个promise返回的状态，这里继承成功状态，打印1
					()=>{
						console.log(1) 
					},()=>{
						console.log(2)
					}
				)

				//如果then传入处理函数，那么会默认返回一个resolved(成功)状态的Promise对象
				new Promise((resolve,reject) => {
					reject()
				}).then(//上个promise传入失败状态，打印2
					()=>{
						console.log(1) 
					},()=>{
						console.log(2)
					}).then(//因为第一个then有处理函数，默认返回一个成功状态，所以打印3
					()=>{
						console.log(3) 
					},()=>{
						console.log(4)
					}
				)



				//如果then传入处理函数，通过处理函数显式的return了一个新的Promise，那么返回这个显式的Promise及其状态
				new Promise((resolve,reject) => {
					reject()
				}).then(//上个promise传入失败状态，打印2
					()=>{
						console.log(1) 
					},()=>{
						console.log(2)
						return new Promise((resolve,reject) => {
							reject()
						})
					}).then(//因为第一个then有处理函数，并手动返回失败状态，所以打印4
					()=>{
						console.log(3) 
					},()=>{
						console.log(4)
					}
				)



			//任务链的一些问题：如何实现中途退出？
			/*new Promise((resolve,reject) => {
				resolve();
			}).then(()=>{
				console.log('登录成功');

				//获取权限
				return new Promise((resolve,reject) =>{

					if (false) {//是否管理员
						resolve();
					}else{
						reject();
					}
					
				})
			},() => {
				console.log('登录失败');
			}).then(()=>{
				console.log('是管理员');
				//获取资源
				return new Promise((resolve,reject) =>{
					resolve();
				})
			},()=>{
				console.log('不是管理员');// 如果不是管理员不需要再执行后面的then方法，如何实现中途退出？
			}).then(()=>{
				console.log('拿到资源');
			},()=>{
				console.log('不能拿资源');
			})*/




			//catch 捕获
			new Promise((resolve,reject) => {
				if (true) {//是否登录成功
					resolve();
				}else{
					reject('登录失败');
				}
				
			}).then(()=>{
				console.log('登录成功');

				//获取权限
				return new Promise((resolve,reject) =>{

					if (false) {//是否管理员
						resolve();
					}else{
						reject('不是管理员');
					}
					
				})
			}).then(()=>{
				console.log('是管理员');
				//获取资源
				return new Promise((resolve,reject) =>{
					resolve();
				})
			}).then(()=>{
				console.log('拿到资源');
			}).catch(err=>{ //catch可以捕获前面所有promise可能出现的reject状态
				console.log(err);
			}).then(()=>{
				console.log('catch后面')
			})

			//需要注意的：
			//1、如果前面的then有第二个函数，则会忽视catch。
			//2、catch也像then一样会返回一个Promise
			



			// Promise.all()
			   //需要请求两个ajax，然后根据这两个ajax返回的结果进行合并才能请求第三个ajax，可用Promise.all()解决。
			let p1 = new Promise((resolve, reject) => {
				setTimeout(()=>{
					resolve(10);
				},1000)
			})

			let p2 = new Promise((resolve, reject) => {
				setTimeout(()=>{
					resolve(20);
				},2000)
			})

			Promise.all([p1,p2]).then(arr => { // Promise.all会等待p1和p2执行完后再执行，arr是p1和p2传入参数的集合
				console.log(arr);
			})


			// Promise.race()
			let p3 = new Promise((resolve, reject) => {
				setTimeout(()=>{
					resolve(10);
				},1000)
			})

			let p4 = new Promise((resolve, reject) => {
				setTimeout(()=>{
					resolve(20);
				},2000)
			})

			Promise.race([p3,p4]).then(arr => { // Promise.race会根据p3和p4其中一个执行完便执行race，后执行的会被忽略
				console.log(arr);
			})




			//以下两个方法可省去这样的操作 new Promise((resolve,reject) =>{resolve();}).then()

			// Promise.resolve()
			Promise.resolve(1).then(v=>{ //打印1
				console.log(v);
			},()=>{
				console.log(2)
			})

			// Promise.reject()
			Promise.reject(2).then(()=>{ //打印2
				console.log(1);
			},v=>{
				console.log(v)
			})


			/*
			最终的解决方案 ES7的 async/await ,省去then方法。
			*/

			async function fn(){  //在函数前面添加async关键字声明此函数为异步函数，然后才能在内部使用await
				try{
					var v = await getValue(10);
					console.log(v);

					var w = await getValue(20);
					console.log(w);

					var y = await getValue(2000);
					console.log(y);
				} catch (e){
					console.log(e);
				}
				
			}

			function getValue(v){
				return new Promise((resolve,reject)=>{
					setTimeout(() => {
						if (v<100) {
							resolve(v * 10);
						}else{
							reject('传入值太大了');
						}
						
					},2000)
				})
			}

			fn();


	</script>
	</script>
</head>
<body>
	
</body>
</html>